### ISSUE TITLE
NAV-RELPOSNED and NAV-PVT support

### ISSUE THREAD

**Issue by dmopalmer** [mayeranalytics/pyUBX#12]
For using the Ardusimple GPS-based heading kit, I need NAV-RELPOSNED and NAV-PVT support.

https://www.ardusimple.com/simplertk2heading-hookup-guide/

**Comment by dmopalmer** [comment]
The definition of NAV-RELPOSNED is different for uBlox-8 and uBlox-9.  I am implementing the uBlox-9 definition.

Page 158 of [ZED-F9P](https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf) vs
Page 329 of
[u-Blox 8](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_(UBX-13003221)_Public.pdf)
shows that the old format is 40 bytes and the new format is 64.

Do you have any hooks in the code that would let both formats coexist, based on the version number (first byte in the payload)?

**Comment by mayeranalytics** [comment]
@dmopalmer When we started this there were no 9-chips and we didn't put in any hooks because there was no way to foresee what was going to be needed. And now, knowing what is needed, it's not easy to do this well from a design point of view. Suggestions are always welcome! 
(In any case: RTK is really nice. We currently have no use-case, though.)

**Comment by brotherdust** [comment]
> The definition of NAV-RELPOSNED is different for uBlox-8 and uBlox-9. I am implementing the uBlox-9 definition.
> 
> Page 158 of [ZED-F9P](https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf) vs
> Page 329 of
> [u-Blox 8](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_(UBX-13003221)_Public.pdf)
> shows that the old format is 40 bytes and the new format is 64.
> 
> Do you have any hooks in the code that would let both formats coexist, based on the version number (first byte in the payload)?

@dmopalmer I, too, am working on adding "uBlox 9"-type messages and was considering the very same thing. My specific use-case is RTK functionality. In the interest of DRY, would you be interested in collaborating on a pull request combining our efforts?

**Comment by dmopalmer** [comment]
> @dmopalmer I, too, am working on adding "uBlox 9"-type messages and was considering the very same thing. My specific use-case is RTK functionality. In the interest of DRY, would you be interested in collaborating on a pull request combining our efforts?

@brotherdust , I have submitted pull request #15 which has:
1) Make it a module (incorporating my PR #14)
2) Add RELPOSNED and PVT 

I also included helper member functions in RELPOSNED and PVT classes.  There should be a better way to incorporate these, since, e.g., you would like to have the iTOW formatter (or something like it) available for every message that needs it.

For doing the versioning, the YAGNI principle would say don't do anything until somebody with a uBlox-8 needs RELPOSNED.

You have't pushed any changes to your ubx-v27-updates branch, so I don't know what's in them.  What messages did you add?  Apart from RELPOSNED and PVT merging should be easy, and maybe automatic.

We should wait for @mayeranalytics to chime in to see whether it is best to wait for the PR to be accepted to the upstream before you try merging.

**Comment by brotherdust** [comment]
> You have't pushed any changes to your ubx-v27-updates branch, so I don't know what's in them. What messages did you add? Apart from RELPOSNED and PVT merging should be easy, and maybe automatic.

@dmopalmer I'm still working on the changes, but here's what I have added or will add to NAV (no particular order):

- POSECEF
- STATUS
- HPPOSECEF
- HPPOSLLH
- SVIN
- SIG
- POSLLH

In regards to configuration, I'm hesitant to use the deprecated CFG messages and want to use CFG-VALGET CFG-VALSET, but there's no scaffolding for it in this library. The reason I would want to have this capability is so that I may initiate or cancel a survey-in. I haven't gotten that far yet, but it's something I'm considering.

**Comment by dmopalmer** [comment]
Adding messages to NAV is straightforward.

I haven't looked at the details, but it appears that the variable-length CFG-VALGET/SET messages may require extending the scaffold with additional hooks.  These would be easy to add to the python code, but making them part of the C++ package generation would require implementing them in C++.
