### ISSUE TITLE
Code is not packaged as a module

### ISSUE THREAD

**Issue by dmopalmer** [mayeranalytics/pyUBX#13]
The code is not packaged as a module.  (See the [packaging guide](https://packaging.python.org).  Ideally I would be able to do something like:
```
(bash)$ pip install /path/to/pyUBX
(bash)$ python
>>> import pyUBX
>>> manager = pyUBX.UBXManager(serial_port)
```
and so on.  This lets you use the code with other software (such as a snazzy map display).

Instead, the M.O. of using it seems to be to cd into the pyUBX directory before running python, which makes it hard to integrate.

I will be tackling this after finishing support for relposNED.  Any tripwires I want to avoid to keep compatible with your use cases?  (Or objections to me doing this?  It will involve moving directories around.)

Thanks.

**Comment by mayeranalytics** [comment]
@dmopalmer Go for it!
