### ISSUE TITLE
Problem when starting UBX Manager

### ISSUE THREAD

**Issue by vo3xel** [mayeranalytics/pyUBX#6]
Hello,

I'm trying to setup my device with the following code:

`
import serial
from UBXManager import UBXManager
ser = serial.Serial('COM4', 115200, timeout=None)
manager = UBXManager(ser, debug=True)
manager.start()
`

I'm getting the following error:
`
Traceback (most recent call last):
  File "c:/projects/pyUBX/start.py", line 4, in <module>
    manager = UBXManager(ser, debug=True)
  File "c:\projects\pyUBX\UBXManager.py", line 28, in __init__
    from UBXMessage import UBXMessage
  File "c:\projects\pyUBX\UBXMessage.py", line 9, in <module>
    import UBX
  File "c:\projects\pyUBX\UBX\__init__.py", line 1, in <module>
    from UBX.ACK import *
  File "c:\projects\pyUBX\UBX\ACK.py", line 3, in <module>
    from UBXMessage import initMessageClass, addGet
ImportError: cannot import name 'initMessageClass' from 'UBXMessage' (c:\projects\pyUBX\UBXMessage.py)
`

Do you have any ideas how to fix it?

Thank you for your work!

BR Michael

**Comment by mcmayer** [comment]
I'm getting this too, but only if there's no communication with the device!
The error message in that case should be better.

**Comment by mcmayer** [comment]
It's a circular dependency problem. I need to look into this with a GPS device attached.
Try removing `import UBX` in line 9 of `UBXMessage.py`.
I just pushed a new version (risky: totally untested).

**Comment by vo3xel** [comment]
Thank you very much, that was a good hint. I works now for me,

thank you for your quick answer and the fix.

BR Michael
